{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Najpopularniejsze filmy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (movie_id) (rate({service_name=\"screening_service\"} |~ \"GET /screenings.*movie_id=\" [1m]))"
    }
   ]
  },
  {
   "title": "Ostatnie błędy",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"/booking_service\"} \n| json \n| status >= 500 \n| line_format \"{{.method}} {{.path}} ({{.status}}): {{.msg}}\""
    }
   ]
  },
  {
   "title": "Aktualne rezerwacje/minutę",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({service_name=\"/booking_service\"} |~ \"POST /bookings\" [1m]))"
    }
   ]
  },
  {
   "title": "Liczba zarejestrowanych użytkowników",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({service_name=\"/user_service\"} |~ \"POST /users\" [1m]))"
    }
   ]
  }
 ]
}