{
 "title": "aaa",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Ilość zapytań do serwisów",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container_name=\"/screening_service\"}[1m])"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({container_name=\"/movie_service\"}[1m])"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({container_name=\"/booking_service\"}[1m])"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({container_name=\"/notification_service\"}[1m])"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({container_name=\"/user_service\"}[1m])"
    }
   ]
  },
  {
   "title": "Ilość błędów i zapytań",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name) (count_over_time({job=\"fluentbit\"} |= \"ERROR\" |= \"Exception\" [1m]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum by (service_name) (count_over_time({job=\"fluentbit\"}[1m]))",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "Aktualne rezerwacje/minutę",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({container_name=\"/booking_service\"} |~ \"POST /bookings\" [1m]))"
    }
   ]
  },
  {
   "title": "Liczba wykonywanych rezerwacji użytkowników",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container_name=\"/booking_service\"} |= \"POST\" [1m])"
    }
   ]
  },
  {
   "title": "Błędy przy tworzeniu nowego użytkownika",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time({container_name=\"/user_service\"} |= \"400\" |= \"POST\" [5m])"
    }
   ]
  },
  {
   "title": "Wysłane maile i sms'y",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time({container_name=\"/notification_service\"} |= \"Email sent\" [1m])",
     "legendFormat": "Email"
    },
    {
     "expr": "count_over_time({container_name=\"/notification_service\"} |= \"SMS sent\" [1m])",
     "legendFormat": "SMS"
    }
   ]
  }
 ]
}